export const cardServicesData = [
  {
    id: 1,
    logo: "fas fa-download",
    title: "Cloud Computing.",
    img: "./images/cloud.jpg",
    info: "Cloud transformation is the comprehensive process of moving your work to the cloud including migration of applications, software programs, desktops, data, or an entire IT infrastructure in full alignment with the business objectives of your company.",
  },
  {
    id: 2,
    logo: "fas fa-user-check",
    title: "Networking",
    img: "./images/networking.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 3,
    logo: "fas fa-money-check-alt",
    title: "NOC Support",
    img: "./images/support.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 4,
    logo: "fab fa-amazon-pay",
    title: "IT Product Sale",
    img: "./images/sale.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 5,
    logo: "fas fa-hand-holding-usd",
    title: "Desktop Support",
    img: "./images/desktop.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 6,
    logo: "fas fa-globe",
    title: "Database Management",
    img: "./images/dbms.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 7,
    logo: "fas fa-globe",
    title: "Admin Support",
    img: "./images/admin.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 8,
    logo: "fas fa-globe",
    title: "EndPoint Security",
    img: "./images/endpointsecurity.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
  {
    id: 9,
    logo: "fas fa-globe",
    title: "Infrastructure Management",
    img: "./images/inframanagent.jpg",
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etquia quis?",
  },
];
